apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python-service
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 5000
  selector:
    app: python
